spring:
  application:
    # 服务名
    name: spring-cloud-pay-provider
  cloud:
    nacos:
      discovery:
        # nacos
        server-addr: 127.0.0.1:8848
    # 服务治理
    sentinel:
      transport:
        dashboard: localhost:8888
server:
  # 端口号
  port: 8070

management:
  # 健康检查
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: springbootdemo.log
  path: 'D:\work\code\spring-cloud-parent\log\ '