spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.lhw.shop.DubboImpl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
