spring:
  application:
    name: spring-cloud-dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        # nacos
        server-addr: 127.0.0.1:8848
    # 服务治理
    sentinel:
      transport:
        dashboard: localhost:8888

dubbo:
  scan:
    base-packages: com.wei.shop.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

server:
  port: 8091

endpoints:
  dubbo:
    enabled: true
management:
  health:
    dubbo:
      status:
        defaults: memory
        extras: threadpool
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
    root: INFO
  path: ../../log